FROM certbot/certbot:latest

CMD ["certonly","--webroot","--webroot-path=/var/www/certbot","--email","satnetuser001@gmail.com","--agree-tos","--no-eff-email","--cert-name","symfonyweatherreminder.mooo.com","-d","symfonyweatherreminder.mooo.com","-d","www.symfonyweatherreminder.mooo.com","-d","api.symfonyweatherreminder.mooo.com"]